### ISSUE TITLE
5 blank rectangles, categories does nothing

### ISSUE THREAD

**Issue by arnoldsecret** [altinselimi/monimo#16]
This issue has been reported on the Reddit thread, but it still persists here.

![untitled](https://user-images.githubusercontent.com/41223243/45758185-9d2dc800-bc57-11e8-8d30-f926ba637fe6.png)

OS is Windows 8.1.

**Comment by altinselimi** [comment]
This is reported by users that are using the app from the following countries:

India, Brazil, Mexico, Singapore, Honk Kong. If you fall under any of these, its because the API is blocking requests from these countries. A fix is underway and will probably land later tonight.

**Comment by sergioreynel** [comment]
So has this been fixed yet I want to use your program as it seems interesting but i'm having this same problem. (in mexico btw)

**Comment by altinselimi** [comment]
Unfortunately this issue is still there in 2.5, even though we made a lot of efforts to fix this. It happens because masterani API uses cloudflare which automatically blocks users from some countries. At the moment the only workaround is using a VPN.

**Comment by arnoldsecret** [comment]
so, the other solution is to use another API if possible?

**Comment by altinselimi** [comment]
If anybody is willing to make such API that is. Or use a nodejs server which would simulate the requests from another location (kinda like a proxy API).

**Comment by zomars** [comment]
This issue should be kept open
