### ISSUE TITLE
No Thumbnails in Continue Watching

### ISSUE THREAD

**Issue by AvidVideoGameFanatic** [altinselimi/monimo#26]
After the new update, for some reason all of the thumbnails in my Continue Watching area are blank. It's weird as it's only that area, and if I search for shows individually, their thumbnails aren't missing
![weirdbug](https://user-images.githubusercontent.com/33430404/46499116-2cf17b80-c7ed-11e8-8034-5188463ad7d6.png)

**Comment by shpetimselaci** [comment]
On what OS are you?

**Comment by AvidVideoGameFanatic** [comment]
> On what OS are you?

I'm on Windows

**Comment by shpetimselaci** [comment]
Which version?

**Comment by AvidVideoGameFanatic** [comment]
Windows 10 Home

**Comment by shpetimselaci** [comment]
Probably because of the old version of Monimo.
Please go to C:\Users\<yourUser>\AppData\Roaming\<yourAppName>\Cache , and delete the cached files.
It will probably remove your 'Continue Watching' series, but there's no other solution.

**Comment by AvidVideoGameFanatic** [comment]
Thank you! That fixed it!
It's not a big deal to lose my 'Continue Watching' area because I keep track of all that on MAL anyways lol.

Thanks once again!
