### ISSUE TITLE
Feature Request - Skip back 10 seconds

### ISSUE THREAD

**Issue by AStartledRaccoon** [altinselimi/monimo#29]
I think it'd be a great idea to implement a feature like this, similar to most players on popular streaming sites. Sometimes I'm not always fully paying attention and find that I want to skip back a bit like I can on 9anime or the like, but I can't. Anyway it would be good to have the skip maybe linked to an arrow key press or a button? Thanks!

**Comment by altinselimi** [comment]
This is a good idea, and is probably going to be in the next version when we give a complete overhaul of video controls. Look forward to 2.5 👍
