### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by Vangelis27** [altinselimi/monimo#30]
After launching the program an error pop-up:
![annotation](https://user-images.githubusercontent.com/11654086/46729951-7596b200-cc8f-11e8-8687-9ec210c4fe20.png)

**Comment by Vangelis27** [comment]
I manually updated to the latest update (0.2.3) and the error is gone. The version that i was using that made the error pop-up was 0.2.0

**Comment by altinselimi** [comment]
We are having troubles with updating app automatically, so until v2.5 you can excpect these breaking changes. Doing these in a separate branch would be better but we want to make sure that everything is working on master before 2.5.
