### ISSUE TITLE
Trakt Integration [Feature]

### ISSUE THREAD

**Issue by spawnpoint** [altinselimi/monimo#32]
Would be great to have trakt integration especially since they have an API that you can use.

https://trakt.docs.apiary.io/#

**Comment by altinselimi** [comment]
Well there are a lot of API-s we could use, but none of them offers us the possibility to safely create URL's which would then give us the links to the videos. So at the moment we are sticking with Masterani. As soon as someone wants to help the project move forward, we could probably make a hybrid API. Thanks for the suggestion anyway.
