### ISSUE TITLE
Attack On Titan S3 episodes missing

### ISSUE THREAD

**Issue by Vangelis27** [altinselimi/monimo#38]
![annotation 4](https://user-images.githubusercontent.com/11654086/47255751-65948480-d47e-11e8-975c-aa4caf144d11.png)

**Comment by altinselimi** [comment]
Download latest episode on monimoapp.com . The version you currently have has a bug which is fixed now.

**Comment by Vangelis27** [comment]
I downloaded and installed the latest version and it still missinig 2 episodes
