### ISSUE TITLE
No linux build for the last version

### ISSUE THREAD

**Issue by Artish357** [altinselimi/monimo#45]
There's no linux build for the latest version, and when compiled from source, i get the following error:

```
Unhandled rejection Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/altinselimi/monimo/releases/download/v0.2.4/latest-linux.yml): HttpError: 404 Not Found                                                                                                                     
"method: undefined url: https://github.com/altinselimi/monimo/releases/download/v0.2.4/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n" 
```

The search doesn't work as well but i don't know if it's related. When i try to search i just get this:
![image](https://user-images.githubusercontent.com/13354036/49751857-902fdc00-fc7c-11e8-8e1e-4521b6b4c248.png)

**Comment by Artish357** [comment]
![image](https://user-images.githubusercontent.com/13354036/49764376-3e4b7e00-fc9d-11e8-830b-7b08ed723488.png)

**Comment by Artish357** [comment]
Actually the search issue is resolved in the development branch. Sorry for that.

Still, a linux build will be very nice!

**Comment by Artish357** [comment]
I'm spamming your issues at this point and I'm very very sorry, but I just found out that development is behind master. Attaching a pull request to fix search on the last version. #46

**Comment by shpetimselaci** [comment]
@Artish357 , can you please create a build and send it to us?

**Comment by Artish357** [comment]
While i could just make a build from master source code and archive it, i was looking into creating appimages and apparently electron has a way of bundling them https://github.com/AppImage/AppImageKit/wiki/Bundling-Electron-apps
It would require some fiddling with npm though, and it's a new technology for me, so I'm afraid that i might break something
