### ISSUE TITLE
New source for anime

### ISSUE THREAD

**Issue by killoid** [altinselimi/monimo#59]
how about animepahe.com? imo this website is really good!

**Comment by altinselimi** [comment]
Hey thanks, that looks awesome. Will look into this today 😄 !

**Comment by altinselimi** [comment]
@killoid There's land ⚓️ !!!
It looks very good for our purposes, but its a bit limited compared to Masterani, as it doesn't offer things like **releases** or filtering by **genre**.

I have made a _post_ on r/monimo to ask for help so we can learn about similar services. If something doesn't come up till next week, then we move on with AnimePahe !
